
name: Build with Clang

on:
  push:
    branches: development/Lexerprototypev2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
      - run: sudo apt install make -y
      - run: make install
