name: Install Clang on Development Branch

on:
  push:
    branches:
      - development/Lexerprototypev2

jobs:
  install-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Clang
        uses: llvm/llvm-project-actions/setup-llvm@v1
        with:
          llvm-version: 16.0.0  # Replace with your desired version

      - name: Make Install
        run: make install

